### ISSUE TITLE
I'm not noticing consistent movement in the demo like I've seen in the project page with box editing

### ISSUE THREAD

**Issue by ninjasaid2k** [shariqfarooq123/LooseControl#1]
![ezgif com-gif-maker](https://github.com/shariqfarooq123/LooseControl/assets/99513716/7a4e7ed7-ba9d-4c95-85c0-d810ab045f3c)
with style-lock
![ezgif com-gif-maker](https://github.com/shariqfarooq123/LooseControl/assets/99513716/f2b946b5-c50c-4d97-a39f-1d920e837161)
my final frame's box position:
 
![image](https://github.com/shariqfarooq123/LooseControl/assets/99513716/9d3179ec-e623-418d-a785-60ea1936c60e)
kind of disappointing, I was hoping to see something like this

https://github.com/shariqfarooq123/LooseControl/assets/99513716/4d5e9544-576f-40fe-9df8-1e22c8e49103

**Comment by olliacc** [comment]
I've had this error: 
![image](https://github.com/shariqfarooq123/LooseControl/assets/152759188/a5eeb738-2f95-4b3a-8cb3-f495cc2a8b61)
I'm not sure this project page exaggerated the capabilities or it's not working well right now.

**Comment by shariqfarooq123** [comment]
The interface to the model is still a bit experimental. I am glad you figured it out though!
